
#ifndef CTSKIN_H
#define CTSKIN_H

#include "base/skin.h"

using namespace GUI;


enum CTStyleBoxList {

	CT_SB_BEGIN=SB_MAX,	
	SB_PATTERN_EDITOR_CURSOR,
	SB_ORDERLIST_CURSOR,
	SB_MAIN_STACK_FRAME,
	SB_TOP_STACK_FRAME,
	SB_PLAYBACK_BUTTON_NORMAL,
	SB_PLAYBACK_BUTTON_PRESSED,
	SB_PLAYBACK_BUTTON_HOVER,
	SB_PLAYBACK_BUTTON_FOCUS,
	
	CT_SB_MAX
};
	
enum CTColorList {

	CT_COLOR_BEGIN=SB_MAX,
	COLOR_PATTERN_EDITOR_ROW_HL_SELECTED,
	COLOR_PATTERN_EDITOR_BG_SELECTED,
	COLOR_PATTERN_EDITOR_FONT_SELECTED,
	COLOR_PATTERN_EDITOR_ROW_HL_MAJOR,
	COLOR_PATTERN_EDITOR_ROW_HL_MINOR,
	COLOR_PATTERN_EDITOR_BG,
	COLOR_PATTERN_EDITOR_FONT,
	COLOR_PATTERN_EDITOR_FONT_MUTE,
	COLOR_PATTERN_EDITOR_FONT_SOLID,
	COLOR_PATTERN_EDITOR_FONT_CLONED,
	COLOR_PATTERN_EDITOR_SEPARATOR,
	COLOR_PATTERN_EDITOR_ROWS,
	COLOR_PATTERN_EDITOR_ROWS_CURRENT,	
	COLOR_PATTERN_EDITOR_TOP,
	COLOR_PATTERN_EDITOR_TOP_MUTE,
	COLOR_PATTERN_EDITOR_TOP_SELECTED,
	COLOR_PATTERN_EDITOR_FOCUS,
	
	COLOR_ORDERLIST_BG,
	COLOR_ORDERLIST_PLAYED_ORDER,
	COLOR_ORDERLIST_ORDER,
	COLOR_ORDERLIST_FOCUS_FRAME,
	COLOR_ORDERLIST_PATTERN,
	
	COLOR_SAMPLE_EDITOR_BG,
	COLOR_SAMPLE_EDITOR_BG_SEL,
	COLOR_SAMPLE_EDITOR_FG,
	COLOR_SAMPLE_EDITOR_FG_SEL,
	COLOR_SAMPLE_EDITOR_LOOP_BG,
	COLOR_SAMPLE_EDITOR_LOOP_BG_SEL,
	COLOR_SAMPLE_EDITOR_LOOP_FG,
	COLOR_SAMPLE_EDITOR_LOOP_FG_SEL,
	COLOR_SAMPLE_EDITOR_CENTER,
	COLOR_SAMPLE_EDITOR_CENTER_SEL,
	COLOR_SAMPLE_EDITOR_NOSAMPLE,
		
	COLOR_SAMPLE_POS_MINVOL,
	COLOR_SAMPLE_POS_MAXVOL,
	
	COLOR_SAMPLETABLE_BG,
	COLOR_SAMPLETABLE_SOLID,
	COLOR_SAMPLETABLE_FG,
	COLOR_SAMPLETABLE_FOCUS,
	COLOR_SAMPLETABLE_CURSOR,
	
	COLOR_ENVELOPE_LOOP,
	COLOR_ENVELOPE_SUSTAIN_LOOP,
	COLOR_ENVELOPE_BG,
	COLOR_ENVELOPE_POINT,
	COLOR_ENVELOPE_FONT,
	COLOR_ENVELOPE_SCALE,
	COLOR_ENVELOPE_LINE,
	
	COLOR_VU_BG,
	COLOR_VU_MIN,
	COLOR_VU_MAX,
	
	COLOR_PLAYBACK_BUTTON_ARROW_COLOR,
	
	CT_COLOR_MAX
	
};

enum CTConstantList {

	CT_C_BEGIN=C_MAX,
	C_PATTERN_EDITOR_COLUMN_SEPARATION,
	C_PATTERN_EDITOR_ROW_SEPARATION,
	C_ORDERLIST_ROW_SEPARATION,
	C_SAMPLETABLE_ROW_SEPARATION,
	C_PLAYBACK_BUTTON_ARROW_SIZE,
	C_PLAYBACK_BUTTON_DISPLACEMENT,
	C_SAMPLE_POSITON_ARROW_SIZE,
	C_PATTERN_EDITOR_OSCS_HEIGHT,
	CT_C_MAX
};
	
enum CTFontList {

	CT_FONT_BEGIN=FONT_MAX,
	FONT_PATTERN_EDITOR,
	FONT_PATTERN_EDITOR_TOP,
	FONT_PATTERN_EDITOR_ROWS,
	FONT_ORDERLIST,
	FONT_SAMPLETABLE,
	FONT_ENVELOPE,
	CT_FONT_MAX
};

enum CTBitmapList {

	CT_BITMAP_BEGIN=BITMAP_MAX,
	BITMAP_PATTERN_EDITOR_TRACK_POPUP,
	BITMAP_PATTERN_EDITOR_TRACK_POPUP_PRESSED,

	CT_BITMAP_MAX

};


class CTSkin  : public Skin {


	virtual void set_default_extra();	
public:
	

	CTSkin();
	~CTSkin();	

};



#endif
